export const ROLES = Object.freeze({
  ADMIN: 1,
  CONSULTANT_JMO: 2,
  MEDICAL_OFFICER: 3,
  LABORATORY_OFFICER: 4,
  CLERICAL_OFFICER: 5,
  COURT_LIAISON_OFFICER: 6,
  RESEARCH_OFFICER: 7,
  DATA_ENTRY_OPERATOR: 8,
});

export const PERMISSIONS = Object.freeze({
  DASHBOARD: Object.values(ROLES),
  PATIENT_READ: [
    ROLES.ADMIN,
    ROLES.CONSULTANT_JMO,
    ROLES.MEDICAL_OFFICER,
    ROLES.CLERICAL_OFFICER,
    ROLES.RESEARCH_OFFICER,
    ROLES.DATA_ENTRY_OPERATOR,
  ],
  PATIENT_CREATE: [
    ROLES.ADMIN,
    ROLES.CONSULTANT_JMO,
    ROLES.MEDICAL_OFFICER,
    ROLES.CLERICAL_OFFICER,
    ROLES.DATA_ENTRY_OPERATOR,
  ],
  PATIENT_UPDATE: [
    ROLES.ADMIN,
    ROLES.CONSULTANT_JMO,
    ROLES.CLERICAL_OFFICER,
    ROLES.DATA_ENTRY_OPERATOR,
  ],
  CASE_READ: Object.values(ROLES),
  CASE_CREATE: [
    ROLES.ADMIN,
    ROLES.CONSULTANT_JMO,
    ROLES.MEDICAL_OFFICER,
    ROLES.DATA_ENTRY_OPERATOR,
  ],
  CASE_STATUS_UPDATE: [ROLES.ADMIN, ROLES.CONSULTANT_JMO],
  POSTMORTEM_READ: [ROLES.ADMIN, ROLES.CONSULTANT_JMO, ROLES.MEDICAL_OFFICER],
  POSTMORTEM_WRITE: [ROLES.ADMIN, ROLES.CONSULTANT_JMO, ROLES.MEDICAL_OFFICER],
  POSTMORTEM_ISSUE: [ROLES.ADMIN, ROLES.CONSULTANT_JMO],
  EVIDENCE_READ: [
    ROLES.ADMIN,
    ROLES.CONSULTANT_JMO,
    ROLES.MEDICAL_OFFICER,
    ROLES.LABORATORY_OFFICER,
  ],
  EVIDENCE_WRITE: [ROLES.ADMIN, ROLES.CONSULTANT_JMO, ROLES.MEDICAL_OFFICER],
  REPORT_READ: [
    ROLES.ADMIN,
    ROLES.CONSULTANT_JMO,
    ROLES.MEDICAL_OFFICER,
    ROLES.CLERICAL_OFFICER,
  ],
  REPORT_CREATE: [ROLES.ADMIN, ROLES.CONSULTANT_JMO, ROLES.MEDICAL_OFFICER],
  REPORT_APPROVE: [ROLES.ADMIN, ROLES.CONSULTANT_JMO],
  STAFF_READ: [ROLES.ADMIN, ROLES.CONSULTANT_JMO, ROLES.MEDICAL_OFFICER],
  STAFF_WRITE: [ROLES.ADMIN],
  POLICE_READ: [
    ROLES.ADMIN,
    ROLES.CONSULTANT_JMO,
    ROLES.MEDICAL_OFFICER,
    ROLES.CLERICAL_OFFICER,
    ROLES.COURT_LIAISON_OFFICER,
  ],
  POLICE_WRITE: [ROLES.ADMIN, ROLES.CLERICAL_OFFICER, ROLES.COURT_LIAISON_OFFICER],
  AUDIT_READ: [ROLES.ADMIN],
  USER_MANAGE: [ROLES.ADMIN],
});

export function hasPermission(user, permission) {
  return Boolean(user && permission.includes(user.role_id));
}
